### PR TITLE
Factor variance

### LINKED ISSUE #43: [FR] Factors need a variance slot

### PR DESCRIPTION
**Pull request by nickhaf**
closes #43

### CODE REVIEW

**Comment by aaronpeikert** [comment]
Variance should usually be a Float, no?

**Comment by nickhaf** [comment]
Yes, noticed already, working on it :D

**Review by aaronpeikert — CHANGES_REQUESTED** [review]
Please add an extractor for factor_variance as well.

Even in tests, it is not good style to access fields directly (though maybe I did it somewhere myself).

**Comment by nickhaf** [comment]
Added an extractor for factor variance. Still a lot more needed for other arguments, will update them bit by bit

**Review by aaronpeikert — APPROVED** [review]

**Pull request merged**
