### PR TITLE
nicer `show` methods

### PR DESCRIPTION
**Pull request by Maximilian-Stefan-Ernst**

### CODE REVIEW

**Comment by Maximilian-Stefan-Ernst** [comment]
Please just merge @aaronpeikert  if there are no issues with this

**Comment by Maximilian-Stefan-Ernst** [comment]
closes #75

**Comment by Maximilian-Stefan-Ernst** [comment]
Nooooo, the doctests have to be fixed...

**Comment by aaronpeikert** [comment]
> Please just merge @aaronpeikert if there are no issues with this

What else would I do?

> Nooooo, the doctests have to be fixed...

But of course there are issues with this.

**Comment by aaronpeikert** [comment]
@Maximilian-Stefan-Ernst, thank you for putting in the work, but this should really not have been merged without review.

You are, of course, correct in #90 that with non-standard show methods, the constructors must be tested separately. Also, I am not sure why the print methods would print the types rather than values. In fact, what I dislike most about the standard print methods is the emphasis on types.

Also, these show methods violate the axiom that the result of print should, when executed, recreate the object printed. Sure enough, often, this does not make sense, but here, it would have been easily possible:
```
Factor(n_variables = 2, loadings = [1, 0.4])
# prints:
Factor(
   n_sample = missing,
   n_variables = 2,
   loadings = [1, 0.4],
   error_covariances_within = [0, 0]
   error_covariances_between = [0, 0]
   crossloadings_incoming = [0, 0]
   crossloadings_outgoing = [0, 0]
)
```

**Comment by Maximilian-Stefan-Ernst** [comment]
Okay, I will wait for review next time. I read the comment "what else should I do than merge" as "reviewed".

I tried your suggested solution, but it is not feasible for those types. Maybe if your model is really easy this makes sense, but if it is more complex, it becomes very messy and much more work would be necessary to make this work (of course feel free to implement it if you have the time :D).

I think especially for structs just showing the names of the fields and their types is quite helpful. First, it directly gives the user feedback what fields they can assess and what those fields look like (vectors, booleans, taxons, etc.) Second, the type of the field can often give all the information a user wants from a print method (if a record is printed, we typically only care about if the object is sensible, for example, if some field is `Missing` rather than `Vector{Float64}`, we can see that our Object is not correct). For all the other information (what the exact loadings are, for example) the user should inspect them.

**Comment by aaronpeikert** [comment]
I think you missed the crucial "if there are no issues with this," for which I have to review it :grin: So, no merges unless review.

Not sure if I agree with your reasoning, but since you put more thought into this than I have, let's go with your solution till we have issues with it.

**Pull request merged**
